from pathlib import Path

from src.utils import MIDFIELD_CONSTRUCTORS


# Added seconds to pit-loss window when scanning for nearby rivals.
PROXIMITY_MARGIN_S = 5.0
# Sensitivity sweep values for the rival-detection proximity margin.
PROXIMITY_MARGIN_SENSITIVITY_S = [3.0, 5.0, 8.0]
# Whether Red Bull, Ferrari, and Mercedes are eligible rival candidates.
INCLUDE_BIG_THREE_AS_RIVALS = True
# Caution-lap TyreLife increment multipliers to test in degradation encoding.
LAMBDA_GRID = [1.0, 0.75, 0.5]
# Number of Monte Carlo iterations per simulation run.
N_ITERATIONS = 10_000
# Conservatism rule anchor used for bias-threshold design.
CONSERVATISM_REFERENCE = "REGULATORY_MAX_FEASIBLE_LAP"
# Optional hard cutoff for insufficiency; None keeps continuous r_b reporting.
INSUFFICIENCY_CUT = None
# Global random seed for reproducible stochastic components.
RNG_SEED = 42
# Identifiability epsilon for treating |B - R_b| as effectively zero.
UNIDENTIFIABLE_EPSILON = 1e-6

# Reconciled caution-lap pace multiplier from diagnostics/
# simulation_step3b_recalibration_and_clean_validation.py (2026-07-20).
# This uses the full-dataset phase3_caution_degradation methodology because the
# locked-sample race-level estimator was underpowered (5/12 races with zero
# caution laps and only 7 defined race ratios).
CAUTION_PACE_RATIO = 1.3162357008284764
# Mean caution-period pit-stop duration (seconds) from reconstructed pit-in to
# next-lap pit-out timestamps on locked races, excluding implausible durations
# >120s (red-flag/session-break artefacts; all 18 exclusions were Japan 2022).
# This corrects the previous 23.1 value which re-reported static pit_loss_s
# rather than measuring caution-period stop durations.
CAUTION_PIT_LOSS_S = 27.67209523809523

# This list was generated by a seeded random draw (seed = RNG_SEED) over years
# surviving the exclusion rule, and corrected on 2026-07-19 because the original
# exclusion rule only checked low_sample and missed invalid_data/insufficient/
# missing degradation-model statuses. Monaco 2022 (HARD and MEDIUM both
# invalid_data) motivated the correction. This was a rule-specification fix
# applied before any downstream use, not a re-draw for outcome reasons.
# See diagnostics/simulation_step2g_lock_archetype_races_corrected.py.
LOCKED_ARCHETYPE_RACES = [
	{"archetype": "Power", "event_name": "Bahrain Grand Prix", "year": 2024, "round": 1},
	{"archetype": "Power", "event_name": "Belgian Grand Prix", "year": 2024, "round": 14},
	{"archetype": "Power", "event_name": "British Grand Prix", "year": 2023, "round": 10},
	{"archetype": "Power", "event_name": "Italian Grand Prix", "year": 2024, "round": 16},
	{"archetype": "Street", "event_name": "Azerbaijan Grand Prix", "year": 2024, "round": 17},
	{"archetype": "Street", "event_name": "Miami Grand Prix", "year": 2024, "round": 6},
	{"archetype": "Street", "event_name": "Monaco Grand Prix", "year": 2023, "round": 6},
	{"archetype": "Street", "event_name": "Singapore Grand Prix", "year": 2022, "round": 17},
	{"archetype": "Technical", "event_name": "Abu Dhabi Grand Prix", "year": 2022, "round": 22},
	{"archetype": "Technical", "event_name": "Hungarian Grand Prix", "year": 2022, "round": 13},
	{"archetype": "Technical", "event_name": "Japanese Grand Prix", "year": 2022, "round": 18},
	{"archetype": "Technical", "event_name": "Spanish Grand Prix", "year": 2023, "round": 7},
]


ROOT = Path(__file__).resolve().parents[2]
# Canonical processed lap-level feature dataset.
BASE_DF_PATH = ROOT / "data" / "processed" / "base_df.csv"
# Per-year degradation fit diagnostics produced by Chapter 3 regeneration.
DEG_RATE_STATS_PATH = ROOT / "data" / "diagnostics" / "deg_rate_full_peryear_stats.csv"
# Calibrated XGBoost test-set predictions used for Phase 3 bias-threshold work.
XGB_TEST_PREDICTIONS_PATH = ROOT / "data" / "models" / "classweight_test_predictions.csv"


# Rivals may be any team including Big Three; only midfield teams may be passed as the
# driver/subject argument to optimiser.py's argmax_strategy once that module exists.
def is_valid_subject(team: str) -> bool:
    return team in MIDFIELD_CONSTRUCTORS